"""
One-time cleanup before Monday deploy:

  1. Clear postmortem/hypotheses.json so the watchlist starts empty.
     The 4/24 data was generated by the old config (ws_scalp + 60min
     time-stop + 4% SL) — those patterns aren't representative of the
     ws_scalp-only regime we're entering.

  2. Delete the test '2026-04-24' sections from the rolling Google Doc.

Safe to re-run; idempotent.
"""
from __future__ import annotations
import os, json, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from postmortem_hypotheses import HYP_PATH
from gdocs_writer import _service, DEFAULT_DOC_ID

# 1. Clear hypotheses
fresh = {'next_id': 1, 'active': [], 'retired': []}
os.makedirs(os.path.dirname(HYP_PATH), exist_ok=True)
with open(HYP_PATH, 'w', encoding='utf-8') as f:
    json.dump(fresh, f, indent=2)
print(f'cleared {HYP_PATH}')

# 2. Strip test sections from the doc.
# Strategy: scan top-level paragraphs, find HEADING_1 paragraphs whose text
# is exactly '2026-04-24' (the test date), then delete from that heading
# through (and not including) the next HEADING_1 — or end-of-doc.
svc = _service()
doc = svc.documents().get(documentId=DEFAULT_DOC_ID).execute()
elems = doc.get('body', {}).get('content', [])

# Build a list of (start, end, style, text) for paragraphs only
paras = []
for e in elems:
    p = e.get('paragraph')
    if not p: continue
    style = p.get('paragraphStyle', {}).get('namedStyleType', '')
    text  = ''.join(r.get('textRun', {}).get('content', '')
                    for r in (p.get('elements') or []))
    paras.append((e['startIndex'], e['endIndex'], style, text))

# Find ranges to delete (each '2026-04-24' heading and everything until next H1)
to_delete = []
i = 0
while i < len(paras):
    s, en, style, txt = paras[i]
    if style == 'HEADING_1' and txt.strip() == '2026-04-24':
        # Range starts at s; ends at start of next HEADING_1 or end-of-doc
        j = i + 1
        while j < len(paras) and paras[j][2] != 'HEADING_1':
            j += 1
        end_idx = paras[j][0] if j < len(paras) else paras[-1][1]
        to_delete.append((s, end_idx))
        i = j
    else:
        i += 1

print(f'found {len(to_delete)} test section(s) to delete')

# Docs API quirk: cannot include the final segment newline in a delete.
# If our range hits the doc end, back off by 1 char.
doc_end = paras[-1][1] if paras else 1
fixed = []
for s, e in to_delete:
    if e >= doc_end:
        e = doc_end - 1
    if e > s:
        fixed.append((s, e))

# Delete in reverse so earlier indices stay valid
requests = [{'deleteContentRange': {'range': {'startIndex': s, 'endIndex': e}}}
            for s, e in sorted(fixed, reverse=True)]

if requests:
    svc.documents().batchUpdate(
        documentId=DEFAULT_DOC_ID,
        body={'requests': requests}).execute()
    print(f'deleted {len(requests)} range(s) from doc')
else:
    print('no test sections found in doc — already clean')

print('done.')
