"""Run a staged tournament for scoring variants.

Stages:
  1. Fast hypothetical lab ranking.
  2. Decision-tape validation for the lab shortlist.
  3. Optional full replay for the decision-tape finalists.

The point of this runner is to keep proxy metrics and true replay metrics in
one artifact so we do not confuse a mechanical lab score with a full backtest.
"""
from __future__ import annotations

from output_paths import output_path

import argparse
import csv
import hashlib
import json
import os
import re
import subprocess
import sys
import time
from collections import Counter
from dataclasses import asdict
from datetime import date
from typing import Any

import backtest_30d_engine as replay
import scoring_variant_lab as slow_lab
import scoring_variant_lab_fast as fast_lab
import scoring_profiles
import simulate_decision_tape
import decision_tape_gates
import step3_replay_cache
import tournament_safety
import worker_policy


HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT_DIR = output_path('postmortem', 'backtests', 'variant_tournaments')
DEFAULT_SOURCE_CSV = os.path.join(
    HERE,
    'postmortem',
    'backtests',
    'engine_replay_2026-04-06_2026-05-01_trades.csv',
)


def _safe_name(name: str) -> str:
    cleaned = re.sub(r'[^A-Za-z0-9_.-]+', '_', name).strip('._')
    if not cleaned:
        cleaned = 'variant'
    digest = hashlib.sha1(name.encode('utf-8')).hexdigest()[:10]
    if len(cleaned) > 24:
        cleaned = cleaned[:24].rstrip('._-')
    return f'{cleaned}_{digest}'


def _short_id(name: str) -> str:
    return hashlib.sha1(name.encode('utf-8')).hexdigest()[:12]


def _num(value: Any, default: float = 0.0) -> float:
    try:
        if value in (None, ''):
            return default
        return float(value)
    except Exception:
        return default


def _read_csv(path: str) -> list[dict]:
    with open(path, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def _row_day(row: dict) -> str:
    for key in ('entry_ct', 'ts_ct', 'day'):
        value = row.get(key)
        if value:
            return str(value)[:10]
    return ''


def _filter_rows(rows: list[dict], start: date, end: date) -> list[dict]:
    out = []
    for row in rows:
        day_s = _row_day(row)
        if not day_s:
            continue
        day = replay._parse_day(day_s)
        if start <= day <= end:
            out.append(row)
    return out


def _market_day_strings(start: str, end: str) -> list[str]:
    return [d.isoformat() for d in replay._market_days(replay._parse_day(start), replay._parse_day(end))]


def _variant_profile(variant: slow_lab.Variant, source: str) -> dict:
    return {
        'name': variant.name,
        'source': source,
        'weights': dict(variant.weights),
        'bias': float(variant.bias or 0.0),
        'notes': [
            'Generated by variant_tournament_runner.py.',
            'Replay-only scoring profile; does not modify live trading behavior.',
        ],
    }


def _write_profile(variant: slow_lab.Variant, out_dir: str, source: str) -> str:
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f'{_short_id(variant.name)}.json')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(_variant_profile(variant, source), f, indent=2, sort_keys=True)
    return path


def _summary(rows: list[dict], skipped: Counter, starting_balance: float, ending_balance: float,
             tickers: list[str]) -> dict:
    wins = [r for r in rows if _num(r.get('pnl')) > 0]
    losses = [r for r in rows if _num(r.get('pnl')) < 0]
    by_ticker = {}
    for ticker in tickers:
        scoped = [r for r in rows if r.get('ticker') == ticker]
        ticker_wins = sum(1 for r in scoped if _num(r.get('pnl')) > 0)
        by_ticker[ticker] = {
            'trades': len(scoped),
            'wins': ticker_wins,
            'losses': sum(1 for r in scoped if _num(r.get('pnl')) < 0),
            'pnl': round(sum(_num(r.get('pnl')) for r in scoped), 2),
            'win_rate_pct': round(100 * ticker_wins / len(scoped), 2) if scoped else None,
        }
    by_day = {}
    for row in rows:
        day = _row_day(row)
        if not day:
            continue
        bucket = by_day.setdefault(day, {'trades': 0, 'wins': 0, 'losses': 0, 'pnl': 0.0})
        pnl = _num(row.get('pnl'))
        bucket['trades'] += 1
        bucket['wins'] += int(pnl > 0)
        bucket['losses'] += int(pnl < 0)
        bucket['pnl'] += pnl
    for bucket in by_day.values():
        bucket['pnl'] = round(bucket['pnl'], 2)
        bucket['win_rate_pct'] = round(100 * bucket['wins'] / bucket['trades'], 2) if bucket['trades'] else None
    worst_day = None
    if by_day:
        worst_key = min(by_day, key=lambda k: by_day[k]['pnl'])
        worst_day = {'day': worst_key, **by_day[worst_key]}
    pnl = round(sum(_num(r.get('pnl')) for r in rows), 2)
    return {
        'trades': len(rows),
        'wins': len(wins),
        'losses': len(losses),
        'win_rate_pct': round(100 * len(wins) / len(rows), 2) if rows else None,
        'pnl': pnl,
        'starting_balance': round(starting_balance, 2),
        'ending_balance': round(ending_balance, 2),
        'by_ticker': by_ticker,
        'by_day': dict(sorted(by_day.items())),
        'worst_day': worst_day,
        'exit_reasons': dict(Counter(r.get('reason') for r in rows)),
        'skipped': dict(skipped),
    }


def _profile_side_from_variant(variant: slow_lab.Variant, row: dict) -> tuple[str, float]:
    original = row.get('original_side')
    score = float(variant.bias or 0.0)
    feats = row.get('model_features') or {}
    for name, weight in variant.weights.items():
        score += float(weight or 0.0) * float(feats.get(name, 0.0) or 0.0)
    if score > 0:
        return 'LONG', score
    if score < 0:
        return 'SHORT', score
    return original, score


def decision_vector_hash(rows_by_day: dict[str, list[dict]], variant: slow_lab.Variant,
                         start: str, end: str) -> str:
    h = hashlib.sha256()
    for day in _market_day_strings(start, end):
        rows = sorted(rows_by_day.get(day, []), key=lambda r: (int(r.get('ts') or 0), r.get('ticker') or ''))
        for row in rows:
            side, _score = _profile_side_from_variant(variant, row)
            h.update(str(row.get('opportunity_id') or '').encode('utf-8'))
            h.update(b'\0')
            h.update(str(side or '').encode('utf-8'))
            h.update(b'\n')
    return h.hexdigest()[:24]


def _decision_trade_row(row: dict, side: str, profile_score: float, balance: float, tickers_count: int) -> dict:
    outcome = (row.get('outcomes') or {}).get(side)
    if not outcome:
        raise ValueError(f"missing outcome for {side}: {row.get('opportunity_id')}")
    entry = float(outcome['entry'])
    exit_price = float(outcome['exit'])
    alloc = round(balance * replay.TRADE_SIZE_PCT / max(1, tickers_count), 2)
    qty = alloc / entry if entry > 0 else 0.0
    gross = (exit_price - entry) * qty
    if side == 'SHORT':
        gross *= -1
    return {
        'opportunity_id': row.get('opportunity_id'),
        'entry_ct': row.get('ts_ct'),
        'exit_ct': outcome.get('exit_ct'),
        'ticker': row.get('ticker'),
        'side': side,
        'original_side': row.get('original_side'),
        'entry': round(entry, 4),
        'exit': round(exit_price, 4),
        'qty': round(qty, 6),
        'alloc': alloc,
        'pnl': round(gross, 4),
        'pnl_pct': outcome.get('pnl_pct'),
        'mfe_pct': outcome.get('mfe_pct'),
        'mae_pct': outcome.get('mae_pct'),
        'held_sec': outcome.get('held_sec'),
        'reason': outcome.get('reason'),
        'score': row.get('score'),
        'profile_score': round(profile_score, 6),
        'conviction': row.get('conviction'),
        'setup_type': row.get('setup_type'),
        'session_phase': row.get('session_phase'),
        'btc_regime': row.get('btc_regime'),
    }


def _simulate_decision_rows(rows_by_day: dict[str, list[dict]], variant: slow_lab.Variant,
                            starting_balance: float, tickers: list[str],
                            start: str, end: str, entry_gate: dict | None = None) -> dict:
    balance = float(starting_balance)
    all_trades: list[dict] = []
    skipped = Counter()
    for day in _market_day_strings(start, end):
        open_until: dict[str, int] = {}
        last_signal_ts: dict[str, float] = {}
        rows = sorted(rows_by_day.get(day, []), key=lambda r: (int(r.get('ts') or 0), r.get('ticker') or ''))
        for row in rows:
            ts = int(row.get('ts') or 0)
            ticker = row.get('ticker')
            if not ticker:
                continue
            if ts < int(open_until.get(ticker, 0) or 0):
                skipped['open_position'] += 1
                continue
            if row.get('conviction') not in replay.MIN_CONVICTION:
                skipped['below_min_conviction'] += 1
                continue
            side, profile_score = _profile_side_from_variant(variant, row)
            missing = decision_tape_gates.missing_gate_features(row, entry_gate)
            if missing:
                skipped[f"entry_gate_missing_features:{','.join(missing)}"] += 1
            else:
                gate_reason = decision_tape_gates.gate_reason(entry_gate, row, side)
                if gate_reason:
                    skipped[f'entry_gate:{gate_reason}'] += 1
                    continue
            setup = row.get('setup_type') or 'unknown'
            key = f'{ticker}:{side}:{setup}'
            cooldown = float(replay.ws_scalp.SETUP_COOLDOWN_SEC.get(setup, 30))
            if ts - float(last_signal_ts.get(key, 0) or 0) < cooldown:
                skipped['cooldown'] += 1
                continue
            trade = _decision_trade_row(row, side, profile_score, balance, len(tickers))
            all_trades.append(trade)
            balance += float(trade['pnl'])
            open_until[ticker] = int(ts + int(trade.get('held_sec') or 0))
            last_signal_ts[key] = float(ts)
    return _summary(all_trades, skipped, starting_balance, balance, tickers)


def _load_decision_rows(args) -> dict[str, list[dict]]:
    shim = argparse.Namespace(
        tickers=args.tickers,
        feed=args.feed,
        quote_mode=args.quote_mode,
        btc_mode=args.btc_mode,
        tape_profile_name=args.tape_profile_name,
        tape_dir=args.tape_dir,
    )
    rows_by_day = {}
    for day in _market_day_strings(args.start, args.end):
        rows_by_day[day] = simulate_decision_tape._read_tape(simulate_decision_tape._tape_path(shim, day))
    return rows_by_day


def _lab_stage(args, variants: list[slow_lab.Variant], source_rows: list[dict]) -> tuple[list[dict], list[slow_lab.Variant]]:
    start = replay._parse_day(args.train_start or args.start)
    end = replay._parse_day(args.train_end or args.end)
    train_rows = _filter_rows(source_rows, start, end)
    results = fast_lab.evaluate(variants, train_rows, args.start_balance, args.lab_batch_size)
    by_name = {variant.name: variant for variant in variants}
    shortlist = [by_name[row['variant']] for row in results[:args.lab_top_n]]
    return results[:args.lab_top_n], shortlist


def _decision_stage(args, variants: list[slow_lab.Variant], rows_by_day: dict[str, list[dict]]) -> list[dict]:
    full_start, full_end = args.start, args.end
    train_start = args.train_start or args.start
    train_end = args.train_end or args.end
    test_start = args.test_start
    test_end = args.test_end
    entry_gate = simulate_decision_tape._load_gate(
        getattr(args, 'entry_gate_json', None),
        getattr(args, 'entry_gate_mode', None),
        getattr(args, 'entry_gate_threshold_pct', None),
    )
    results = []
    for variant in variants:
        full = _simulate_decision_rows(rows_by_day, variant, args.start_balance, args.tickers, full_start, full_end, entry_gate)
        train = _simulate_decision_rows(rows_by_day, variant, args.start_balance, args.tickers, train_start, train_end, entry_gate)
        test = None
        if test_start and test_end:
            test = _simulate_decision_rows(rows_by_day, variant, args.start_balance, args.tickers, test_start, test_end, entry_gate)
        results.append({
            'variant': variant.name,
            'weights': dict(variant.weights),
            'bias': float(variant.bias or 0.0),
            'decision_full': full,
            'decision_train': train,
            'decision_test': test,
            'rank_score': (
                (test or full)['pnl'],
                full['pnl'],
                -abs((train.get('pnl') or 0.0) - ((test or train).get('pnl') or 0.0)),
            ),
        })
    results.sort(key=lambda r: r['rank_score'], reverse=True)
    for idx, row in enumerate(results, 1):
        row['decision_rank'] = idx
        row.pop('rank_score', None)
    return results


def _decision_baselines(args, rows_by_day: dict[str, list[dict]]) -> list[dict]:
    entry_gate = simulate_decision_tape._load_gate(
        getattr(args, 'entry_gate_json', None),
        getattr(args, 'entry_gate_mode', None),
        getattr(args, 'entry_gate_threshold_pct', None),
    )
    baseline_specs = [{'name': 'decision_tape_original_side', 'profile': None, 'path': None}]
    for path in getattr(args, 'baseline_scoring_profile', []) or []:
        baseline_specs.append({
            'name': os.path.splitext(os.path.basename(path))[0],
            'profile': scoring_profiles.load_profile(path),
            'path': path,
        })
    out = []
    for spec in baseline_specs:
        balance = float(args.start_balance)
        all_trades = []
        skipped = Counter()
        for day in _market_day_strings(args.start, args.end):
            day_trades, balance, day_skipped = simulate_decision_tape.simulate_day(
                rows_by_day.get(day, []),
                spec['profile'],
                balance,
                args.tickers,
                entry_gate,
            )
            all_trades.extend(day_trades)
            skipped.update(day_skipped)
        full = _summary(all_trades, skipped, args.start_balance, balance, args.tickers)
        train = None
        test = None
        if args.train_start and args.train_end:
            train = _baseline_range(args, rows_by_day, spec['profile'], entry_gate, args.train_start, args.train_end)
        if args.test_start and args.test_end:
            test = _baseline_range(args, rows_by_day, spec['profile'], entry_gate, args.test_start, args.test_end)
        out.append({
            'baseline': spec['name'],
            'profile': spec['path'],
            'decision_full': full,
            'decision_train': train,
            'decision_test': test,
            'selection_flags': tournament_safety.disqualification_flags(full, train, test),
        })
    return out


def _baseline_range(args, rows_by_day: dict[str, list[dict]], profile: dict | None, entry_gate: dict | None,
                    start: str, end: str) -> dict:
    balance = float(args.start_balance)
    all_trades = []
    skipped = Counter()
    for day in _market_day_strings(start, end):
        day_trades, balance, day_skipped = simulate_decision_tape.simulate_day(
            rows_by_day.get(day, []),
            profile,
            balance,
            args.tickers,
            entry_gate,
        )
        all_trades.extend(day_trades)
        skipped.update(day_skipped)
    return _summary(all_trades, skipped, args.start_balance, balance, args.tickers)


def _run_full_replay(args, variant: slow_lab.Variant, profile_path: str, out_root: str,
                     start: str, end: str, label: str) -> dict:
    artifact_id = _short_id(variant.name)
    variant_dir = os.path.join(out_root, label, artifact_id)
    os.makedirs(variant_dir, exist_ok=True)
    stem = f'engine_replay_{start}_{end}_{artifact_id}_mock_parity'
    summary_path = os.path.join(
        variant_dir,
        f'{stem}_summary.json',
    )
    csv_path = os.path.join(
        variant_dir,
        f'{stem}_trades.csv',
    )
    cache_key = None
    cache_payload = None
    if getattr(args, 'global_full_replay_cache', False):
        cache_key, cache_payload = step3_replay_cache.replay_key(args, variant, profile_path, start, end, label)
        restored = step3_replay_cache.restore(
            getattr(args, 'full_replay_cache_dir', step3_replay_cache.DEFAULT_CACHE_DIR),
            cache_key,
            cache_payload,
            summary_path,
            csv_path,
        )
        if restored:
            return {
                'label': label,
                'start': start,
                'end': end,
                'variant': variant.name,
                'profile': profile_path,
                'out_dir': variant_dir,
                'elapsed_seconds': 0.0,
                'returncode': 0,
                'reused_global_cache': True,
                'cache_key': cache_key,
                'cache_meta': restored.get('cache_meta'),
                'summary': restored.get('summary'),
                'summary_path': restored.get('summary_path'),
                'csv_path': restored.get('csv_path'),
            }
    if getattr(args, 'reuse_full_replay_summary', False) and os.path.exists(summary_path):
        with open(summary_path, 'r', encoding='utf-8') as f:
            summary = json.load(f)
        return {
            'label': label,
            'start': start,
            'end': end,
            'variant': variant.name,
            'profile': profile_path,
            'out_dir': variant_dir,
            'elapsed_seconds': 0.0,
            'returncode': 0,
            'reused_existing_summary': True,
            'summary': summary,
            'summary_path': summary_path,
            'csv_path': csv_path if os.path.exists(csv_path) else None,
        }
    cmd = [
        sys.executable,
        os.path.join(HERE, 'mock_replay.py'),
        '--start', start,
        '--end', end,
        '--tickers', *args.tickers,
        '--start-balance', str(args.start_balance),
        '--scoring-profile', profile_path,
        '--out-dir', variant_dir,
    ]
    if getattr(args, 'resume_day_checkpoints', False):
        cmd.append('--resume-days')
    if args.entry_gate_mode:
        cmd.extend(['--replay-regime-long-throttle', args.entry_gate_mode])
    if args.entry_gate_threshold_pct is not None:
        cmd.extend(['--replay-regime-threshold-pct', str(args.entry_gate_threshold_pct)])
    if getattr(args, 'brs_failed_followthrough_after_sec', 0.0):
        cmd.extend(['--brs-failed-followthrough-after-sec', str(args.brs_failed_followthrough_after_sec)])
        cmd.extend(['--brs-failed-followthrough-min-mfe-pct', str(getattr(args, 'brs_failed_followthrough_min_mfe_pct', 0.12))])
        cmd.extend(['--brs-failed-followthrough-max-pnl-pct', str(getattr(args, 'brs_failed_followthrough_max_pnl_pct', 0.0))])
    if abs(float(getattr(args, 'brs_tp_multiplier', 1.0) or 1.0) - 1.0) > 1e-12:
        cmd.extend(['--brs-tp-multiplier', str(args.brs_tp_multiplier)])
    if abs(float(getattr(args, 'momentum_tp_multiplier', 1.0) or 1.0) - 1.0) > 1e-12:
        cmd.extend(['--momentum-tp-multiplier', str(args.momentum_tp_multiplier)])
    if abs(float(getattr(args, 'high_conviction_tp_multiplier', 1.0) or 1.0) - 1.0) > 1e-12:
        cmd.extend(['--high-conviction-tp-multiplier', str(args.high_conviction_tp_multiplier)])
    if int(float(getattr(args, 'entry_confirmation_delay_sec', 0.0) or 0.0)) > 0:
        cmd.extend(['--entry-confirmation-delay-sec', str(args.entry_confirmation_delay_sec)])
        cmd.extend(['--entry-confirmation-mode', str(getattr(args, 'entry_confirmation_mode', 'off'))])
        cmd.extend(['--entry-confirmation-setup', str(getattr(args, 'entry_confirmation_setup', 'all'))])
        cmd.extend(['--entry-confirmation-min-favorable-pct', str(getattr(args, 'entry_confirmation_min_favorable_pct', 0.0))])
        cmd.extend(['--entry-confirmation-adverse-pct', str(getattr(args, 'entry_confirmation_adverse_pct', 0.0))])
        cmd.extend(['--entry-confirmation-session-phase', str(getattr(args, 'entry_confirmation_session_phase', 'all'))])
        edge_threshold = getattr(args, 'entry_confirmation_edge_threshold_pct', None)
        rel_threshold = getattr(args, 'entry_confirmation_rel_threshold_pct', None)
        if edge_threshold is not None:
            cmd.extend(['--entry-confirmation-edge-threshold-pct', str(edge_threshold)])
        if rel_threshold is not None:
            cmd.extend(['--entry-confirmation-rel-threshold-pct', str(rel_threshold)])
    if int(float(getattr(args, 'path_failure_after_sec', 0.0) or 0.0)) > 0:
        cmd.extend(['--path-failure-after-sec', str(args.path_failure_after_sec)])
        cmd.extend(['--path-failure-edge-threshold-pct', str(getattr(args, 'path_failure_edge_threshold_pct', 0.0))])
        cmd.extend(['--path-failure-action', str(getattr(args, 'path_failure_action', 'off'))])
        cmd.extend(['--path-failure-setup', str(getattr(args, 'path_failure_setup', 'all'))])
        cmd.extend(['--path-failure-session-phase', str(getattr(args, 'path_failure_session_phase', 'all'))])
        cmd.extend(['--path-failure-window-sec', str(getattr(args, 'path_failure_window_sec', 0))])
        cmd.extend(['--path-failure-reduce-fraction', str(getattr(args, 'path_failure_reduce_fraction', 0.0))])
        rel_threshold = getattr(args, 'path_failure_rel_threshold_pct', None)
        if rel_threshold is not None:
            cmd.extend(['--path-failure-rel-threshold-pct', str(rel_threshold)])
    def _run_cmd(command: list[str]) -> subprocess.CompletedProcess:
        creationflags = 0
        if getattr(args, 'low_priority_replays', False) and os.name == 'nt':
            creationflags = getattr(subprocess, 'BELOW_NORMAL_PRIORITY_CLASS', 0)
        return subprocess.run(command, cwd=HERE, capture_output=True, text=True, creationflags=creationflags)

    started = time.perf_counter()
    proc = _run_cmd(cmd)
    fallback_used = False
    if (
        proc.returncode != 0
        and getattr(args, 'retry_single_worker_on_pool_error', True)
        and 'PermissionError: [WinError 5]' in (proc.stderr or '')
        and '--workers' in cmd
    ):
        fallback_cmd = list(cmd)
        worker_idx = fallback_cmd.index('--workers') + 1
        fallback_cmd[worker_idx] = '1'
        proc = _run_cmd(fallback_cmd)
        fallback_used = True
    else:
        fallback_cmd = None
    elapsed = round(time.perf_counter() - started, 3)
    payload = {
        'label': label,
        'start': start,
        'end': end,
        'variant': variant.name,
        'profile': profile_path,
        'out_dir': variant_dir,
        'elapsed_seconds': elapsed,
        'returncode': proc.returncode,
        'retry_single_worker_on_pool_error': fallback_used,
        'command': cmd,
        'executed_command': fallback_cmd if fallback_used else cmd,
        'stdout_tail': proc.stdout[-4000:],
        'stderr_tail': proc.stderr[-4000:],
    }
    if os.path.exists(summary_path):
        with open(summary_path, 'r', encoding='utf-8') as f:
            payload['summary'] = json.load(f)
        payload['summary_path'] = summary_path
    if os.path.exists(csv_path):
        payload['csv_path'] = csv_path
    if cache_key and cache_payload and os.path.exists(summary_path):
        cached = step3_replay_cache.store(
            getattr(args, 'full_replay_cache_dir', step3_replay_cache.DEFAULT_CACHE_DIR),
            cache_key,
            cache_payload,
            summary_path,
            csv_path,
        )
        if cached:
            payload['cache_key'] = cache_key
            payload['cache_meta'] = cached.get('cache_meta')
    if proc.returncode != 0:
        payload['error'] = 'full replay command failed'
    return payload


def _full_replay_stage(args, variants: list[slow_lab.Variant], run_dir: str) -> list[dict]:
    profile_dir = os.path.join(run_dir, 'profiles')
    full_root = os.path.join(run_dir, 'full_replay')
    source = os.path.join(run_dir, 'tournament_summary.json')
    results = []
    for variant in variants:
        profile_path = _write_profile(variant, profile_dir, source)
        full = _run_full_replay(args, variant, profile_path, full_root, args.start, args.end, 'full')
        train = None
        test = None
        if args.train_start and args.train_end:
            train = _run_full_replay(args, variant, profile_path, full_root, args.train_start, args.train_end, 'train')
        if args.test_start and args.test_end:
            test = _run_full_replay(args, variant, profile_path, full_root, args.test_start, args.test_end, 'test')
        results.append({
            'variant': variant.name,
            'profile': profile_path,
            'full_replay': full,
            'train_replay': train,
            'test_replay': test,
        })
    results.sort(key=lambda r: ((r.get('test_replay') or {}).get('summary') or (r.get('full_replay') or {}).get('summary') or {}).get('pnl', -10**9), reverse=True)
    return results


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description='Run staged scoring-variant tournament.')
    ap.add_argument('--start', default='2026-04-06')
    ap.add_argument('--end', default='2026-05-01')
    ap.add_argument('--train-start', default=None)
    ap.add_argument('--train-end', default=None)
    ap.add_argument('--test-start', default=None)
    ap.add_argument('--test-end', default=None)
    ap.add_argument('--source-csv', default=DEFAULT_SOURCE_CSV)
    ap.add_argument('--tickers', nargs='+', default=replay.TICKERS)
    ap.add_argument('--feed', default='sip')
    ap.add_argument('--quote-mode', default='per-second')
    ap.add_argument('--btc-mode', default='bars')
    ap.add_argument('--tape-dir', default=simulate_decision_tape.DEFAULT_TAPE_DIR)
    ap.add_argument('--tape-profile-name', default='')
    ap.add_argument('--entry-gate-json', default=None)
    ap.add_argument('--entry-gate-mode', default=None)
    ap.add_argument('--entry-gate-threshold-pct', type=float, default=None)
    ap.add_argument('--baseline-scoring-profile', action='append', default=[],
                    help='Optional replay-only profile JSON to include as a baseline in decision-tape reporting.')
    ap.add_argument('--out-dir', default=DEFAULT_OUT_DIR)
    ap.add_argument('--name', default=None)
    ap.add_argument('--start-balance', type=float, default=100000.0)
    ap.add_argument('--extra-elite-variants', type=int, default=0)
    ap.add_argument('--extra-seed', type=int, default=20260503)
    ap.add_argument('--lab-top-n', type=int, default=1000)
    ap.add_argument('--decision-top-n', type=int, default=50)
    ap.add_argument('--full-top-n', type=int, default=10)
    ap.add_argument('--lab-batch-size', type=int, default=5000)
    ap.add_argument('--full-workers', type=int, default=worker_policy.DEFAULT_MAX_WORKERS)
    ap.add_argument('--diverse-finalists-per-family', type=int, default=3)
    ap.add_argument('--disable-diverse-finalists', action='store_true')
    ap.add_argument('--min-trades', type=int, default=50)
    ap.add_argument('--max-trades', type=int, default=100000)
    ap.add_argument('--registry-path', default=tournament_safety.DEFAULT_REGISTRY)
    ap.add_argument('--no-registry', action='store_true')
    ap.add_argument('--skip-full-replay', action='store_true')
    return ap.parse_args()


def main() -> int:
    args = parse_args()
    args.tickers = [t.upper() for t in args.tickers]
    args.full_workers = worker_policy.clamp_workers(args.full_workers)
    started_at = time.perf_counter()
    run_name = args.name or f"tournament_{args.start}_{args.end}_{time.strftime('%Y%m%d_%H%M%S')}"
    run_dir = os.path.join(args.out_dir, _safe_name(run_name))
    os.makedirs(run_dir, exist_ok=True)

    variants = list(slow_lab.VARIANTS)
    if args.extra_elite_variants:
        variants.extend(fast_lab.extra_elite_variants(args.extra_elite_variants, args.extra_seed))

    extra_paths = [args.source_csv, *list(args.baseline_scoring_profile or [])]
    if args.entry_gate_json:
        extra_paths.append(args.entry_gate_json)
    fingerprints = tournament_safety.run_fingerprint(args, extra_paths=extra_paths)
    source_rows = _read_csv(args.source_csv)
    lab_results, lab_variants = _lab_stage(args, variants, source_rows)
    lab_results = tournament_safety.enrich_lab_results(lab_results)

    rows_by_day = _load_decision_rows(args)
    baseline_results = _decision_baselines(args, rows_by_day)
    decision_results = _decision_stage(args, lab_variants, rows_by_day)
    decision_results = tournament_safety.enrich_decision_results(
        decision_results,
        lab_results,
        min_trades=args.min_trades,
        max_trades=args.max_trades,
    )
    decision_variants_by_name = {variant.name: variant for variant in lab_variants}
    if args.disable_diverse_finalists:
        selected_decision_rows = decision_results[:max(0, args.decision_top_n)]
    else:
        selected_decision_rows = tournament_safety.select_diverse_finalists(
            decision_results,
            max(0, args.decision_top_n),
            per_family=max(1, args.diverse_finalists_per_family),
        )
    finalist_variants = [decision_variants_by_name[row['variant']] for row in selected_decision_rows]

    full_replay_results = []
    if not args.skip_full_replay and args.full_top_n > 0:
        full_replay_results = _full_replay_stage(args, finalist_variants[:args.full_top_n], run_dir)
        full_replay_results = tournament_safety.enrich_full_results(full_replay_results, decision_results)

    elapsed = round(time.perf_counter() - started_at, 3)
    payload = {
        'schema_version': 2,
        'run_name': run_name,
        'elapsed_seconds': elapsed,
        'config': vars(args),
        'fingerprints': fingerprints,
        'counts': {
            'variants_total': len(variants),
            'lab_shortlist': len(lab_variants),
            'decision_results': len(decision_results),
            'selected_decision_finalists': len(finalist_variants),
            'full_replay_results': len(full_replay_results),
            'baseline_results': len(baseline_results),
        },
        'method_notes': [
            'lab_results are a hypothetical proxy using mechanical inverse P/L for side flips.',
            'decision_results use captured decision points with precomputed LONG/SHORT paths, open-position blocking, cooldown, and compounding.',
            'full_replay_results are the highest-fidelity stage and should be treated as the backtest verdict.',
            'composite_score penalizes train/test instability, worst-day loss, concentration, and automatic selection flags.',
            'family_id groups near-related weight signatures so finalist selection can avoid replaying many duplicates.',
        ],
        'lab_results': lab_results,
        'baseline_results': baseline_results,
        'decision_results': decision_results,
        'selected_decision_finalists': selected_decision_rows,
        'full_replay_results': full_replay_results,
    }
    out_path = os.path.join(run_dir, 'tournament_summary.json')
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(payload, f, indent=2, sort_keys=True)
    registry_path = None
    if not args.no_registry:
        registry_path = tournament_safety.append_registry(
            tournament_safety.registry_rows(payload, out_path),
            args.registry_path,
        )

    print(json.dumps({
        'out': out_path,
        'registry': registry_path,
        'elapsed_seconds': elapsed,
        'counts': payload['counts'],
        'top_lab': lab_results[0] if lab_results else None,
        'top_decision': decision_results[0] if decision_results else None,
        'top_full_replay': full_replay_results[0] if full_replay_results else None,
    }, indent=2))
    return 0


if __name__ == '__main__':
    import canonical_command_registry as _canonical_commands
    _canonical_commands.enforce_direct_script_allowed(__file__)
    raise SystemExit(main())
